### ISSUE TITLE
Publish 1.0

### ISSUE THREAD

**Issue by benogle** [leejarvis/block-travel#9]
It's not in the package registry! `apm publish` should do it

**Comment by leejarvis** [comment]
Ugh. I'm having a nightmare with this.

Ran `apm publish` which expects that you haven't created the tag already. I created version 1.0.1 to circumvent this and then got prompted for my username and password, which, although completely valid, I get an error for:

```
~/code/block-travel[master]% apm publish 1.0.1
Preparing and tagging a new version ✓
Pushing v1.0.1 tag Username for 'https://github.com': leejarvis
Password for 'https://leejarvis@github.com':
✗
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/leejarvis/block-travel.git/'
```

Can I tell it to use `git@github.com:leejarvis/block-travel.git` without having to change my package?

Realised I was back to step one but didn't want to create a 1.0.2 tag.

Found `--tag` which just magically doesn't work:

```
~/code/block-travel[master]% apm publish -t v1.0.1
Publishing block-travel@v1.0.1 ✗
Creating new version failed: Git tag not found
~/code/block-travel[master]% apm publish -t 1.0.1
Publishing block-travel@1.0.1 ✗
Creating new version failed: Git tag not found
```

**Comment by benogle** [comment]
Can you try `apm login` then try to publish 1.0.1 again? is the git tag pushed? `git push --tags`

**Comment by leejarvis** [comment]
done https://atom.io/packages/block-travel

**Comment by benogle** [comment]
Sorry for the trouble. How did you solve it?

**Comment by leejarvis** [comment]
I had cloned the public repo URL, which is obviously why it was asking me for my username/password. I'm not sure why those didn't work, maybe because I'm using 2fa? 

I guess the publish complained about tags because they weren't pushed. Seems obvious now but maybe it should check if the tag is local and tell the user to push. I should note I was doing all of this a bit hastily as I was quite busy at the time.

Did an `apm login`, updated the origin to the writable repo, pushed the tags, and publish worked fine.
